---
engines:
  csslint:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
      - javascript
      - python
  eslint:
    enabled: true
  fixme:
    enabled: true
  radon:
    enabled: true
ratings:
  paths:
  - "**.css"
  - "**.js"
  - "**.jsx"
  - "**.py"
exclude_paths:
- "backend/hqlib/app/dist/"
- "frontend/node_modules/"
- "frontend/tests/"
- "docs/examples/"
- "backend/tests/unittests/"
- "backend/tests/integrationtests/"
- "backend/tests/qualitytests/"
- ".pylintrc"
