---
engines:
  csslint:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
      - javascript
      - python
  eslint:
    enabled: true
  fixme:
    enabled: true
  radon:
    enabled: true
ratings:
  paths:
  - "**.css"
  - "**.js"
  - "**.jsx"
  - "**.py"
exclude_paths:
- "hqlib/formatting/js/bootstrap.min.js"
- "hqlib/formatting/js/compatibility.js"
- "docs/examples/"
- "tests/unittests/"
- "tests/integrationtests/"
- ".pylintrc"
