sudo: required
dist: trusty
language: java
install:
- pip install -r requirements.txt
- pip install codeclimate-test-reporter
script:
- coverage run --branch tests/run_unittests.py discover -s tests/unittests -p "*_tests.py"
- coverage xml
- CODECLIMATE_REPO_TOKEN=58f7db7da1655acbe50dec6251772d4473dce782808e29b20299d5a7f3fca904 codeclimate-test-reporter
- coverage run --parallel-mode --branch tests/run_integrationtests.py discover -s tests/integrationtests -p "*_tests.py"
- coverage combine .
- coverage xml -o it-coverage.xml
- sonar-scanner -Dsonar.login=$SONAR_TOKEN
addons:
  sonarqube: true
  code_climate:
    repo_token: 58f7db7da1655acbe50dec6251772d4473dce782808e29b20299d5a7f3fca904
env:
  global:
    - secure: mOpbXELefnD2snAx7ie+wQwcF52/ee1n1ILeqjnSunDGHCZzitpYwVR1+hhqXyK0bNy+HdALCXf2rlqzJUvOsQmAYefj19w4K5SzejVd27MVeJ15EFX9NAruRo0Z3qg1jr5s0argFra5JrdXbfGGLWqY7Ejj5ZzG40VlRjKMx88=
