sudo: required
dist: trusty
language: java
install:
- pip install -r python/requirements.txt
- pip install codeclimate-test-reporter
jdk: oraclejdk8
script:
- coverage run --branch python/run_unittests.py discover -s python/unittests -p "*_tests.py"
- coverage xml
- python python/setup.py sdist
- coverage run --branch python/run_integrationtests.py discover -s python/integrationtests -p "*_tests.py"
- coverage xml -o it-coverage.xml
- CODECLIMATE_REPO_TOKEN=58f7db7da1655acbe50dec6251772d4473dce782808e29b20299d5a7f3fca904 codeclimate-test-reporter
- sonar-scanner -Dsonar.login=$SONAR_TOKEN
addons:
  sonarqube: true
  code_climate:
    repo_token: 58f7db7da1655acbe50dec6251772d4473dce782808e29b20299d5a7f3fca904
env:
  global:
    - secure: mOpbXELefnD2snAx7ie+wQwcF52/ee1n1ILeqjnSunDGHCZzitpYwVR1+hhqXyK0bNy+HdALCXf2rlqzJUvOsQmAYefj19w4K5SzejVd27MVeJ15EFX9NAruRo0Z3qg1jr5s0argFra5JrdXbfGGLWqY7Ejj5ZzG40VlRjKMx88=
